XMLTV/xmltv

lib/Configure.pm

Updated config line regex to support values with an exclamation mark "!"

---

grab/it/channel_ids

This commit closes SF Patch #101 "channel_ids for tv_grab_it" 
Credit: yutzhead,  plus a few recent extra channels from me

Updated channel ids - see SF Patches#101

---

grab/combiner/tv_grab_combiner
grab/it/channel_ids

Credit: Robert Högberg
https://sourceforge.net/p/xmltv/patches/93/

tv_grab_combiner leaves temporary files around - see SF Patches #93

---

MANIFEST
Makefile.PL
grab/in_toi/tv_grab_in_toi

Grabber created by Anand Tamariya
https://sourceforge.net/p/xmltv/patches/96/
Modified for better compliance with XMLTV standards.

Grabber for India (SF#96)

---

grab/fi/fi/programme.pm
grab/fi/fi/source/foxtv.pm
grab/fi/test.conf

* add support for total # of episodes
* fix regex in foxtv which broke subtitle, season & episode number extraction
* add a new description parser for ^episode/total .... format

Topic add episode total support

---

grab/uk_tvguide/tv_grab_uk_tvguide

Date not being parsed for certain dates (e.g. "Christmas Eve")  (issue #41)

 Fix nbsp replacing space in certain dates

---

grab/uk_tvguide/tv_grab_uk_tvguide

Fix missing programmes across calendar year change

---

grab/eu_epgdata/tv_grab_eu_epgdata

EPGdata has some fanart, but they were not in the xml file

Include Images from EPGdata

---

grab/fr/tv_grab_fr
grab/uk_tvguide/tv_grab_uk_tvguide

* fix tv_grab_uk_guide : url (https)
* fix tv_grab_fr : url (https)
* fix tv_grab_fr : div replaced by td

fix tv_grab_uk_guide and tv_grab_fr

---

grab/uk_tvguide/tv_grab_uk_tvguide

Add stop time to programmes which cross the GMT->BST transition

fix issue #59 tv_grab_uk_tvguide

---

grab/zz_sdjson_sqlite/tv_grab_zz_sdjson_sqlite

(If yes, please provide the issue number)
…
…
(For example, has this change been discussed on the xmltv-devel mailing list?) …

handle (unlikely) use of --no-download with --list-lineups

---

grab/eu_epgdata/tv_grab_eu_epgdata

Not checked
* cleanup old code
* improve download speed
* fix encoding issues
* fix channel name parsing
* Anchor regular expressions
* Fix copy-paste-error
I'm using this for years with MythTV.
Where have you tested these changes?
------------------------------------
Debian GNU/Linux 10.3 (Buster) (and previously Stretch and Sid)
Perl v5.28.1

Epgdata improvements and cleanup

---

grab/eu_epgdata/tv_grab_eu_epgdata

Downloaded file needs to be unpacked.
Fixes: 23ec05300
No
Fix bug introduced with last PR
no
Where have you tested these …

Fix unpacking includes.zip

---

README.md

It does not.
…
It brings the README in line with Github Standards and gives a more attractive and intutive document for presentation. If this PR is succesful I can follow …

Renamed README -> README.md and amended for markdown support.

---

grab/zz_sdjson_sqlite/fixups.txt
grab/zz_sdjson_sqlite/tv_grab_zz_sdjson_sqlite

Pull in multiple upstream tv_grab_zz_sdjson_sqlite fixes/enhancements.

Update tv_grab_zz_sdjson_sqlite to latest upstream

---

grab/eu_xmltvse/tv_grab_eu_xmltvse

Updates `tv_grab_eu_xmltvse` to use SSL.

Update tv_grab_eu_xmltvse to use SSL

---

xmltv.dtd

Fixes: #134
#134
…
Adds guest attribute to actor credit
…
Lightly tested using tv_validate_file against a modified grabber which provides the guest attribute for actors.

Add guest attribute to actor credit in xmltv.dtd

---

.github/workflows/build.yml

Pull request to add github workflow actions for pushes and pull requests.

Add github workflow actions

---

grab/zz_sdjson_sqlite/tv_grab_zz_sdjson_sqlite

Update tv_grab_zz_sdjson_json to recent commits
…

Update tv_grab_zz_sdjson_sqlite to recent commits

---

grab/zz_sdjson_sqlite/tv_grab_zz_sdjson_sqlite

Update to latest tv_grab_zz_sdjson_sqlite upstream

Update zz sdjson sqlite

---

grab/zz_sdjson_sqlite/tv_grab_zz_sdjson_sqlite

(If yes, please provide the issue number)
…
…
(For example, has this change been discussed on the xmltv-devel mailing list?) …

Update tv_grab_zz_sdjson_sqlite to latest upstream commits

---

grab/zz_sdjson_sqlite/tv_grab_zz_sdjson_sqlite

Pull in upstream fixes for error handling

fix error handling in DB_open

---

.github/workflows/build.yml

No
This PR fixes the github workflow for builds on the Linux platforms.
None
Where have you tested these changes? …

PR for fixing Linux builds with github actions

---

.github/workflows/build.yml

Fixes: #258
#258 
Fixes macOS builds using the workaround for using an older C standard
Where have you tested these changes? …

build.yml: Use workaround for macOS builds of Tk
